apiVersion: v1
kind: ConfigMap
metadata: 
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::351575047322:user/github-ci
      username: github-ci
      group: 
        -system:masters
